development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: phonebook
  pool: 5
  port: 5432

test: &test
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: phonebook
  pool: 5
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: phonebook
  pool: 5
  username: dbuser
  password: password
  port: 5432

cucumber:
  <<: *test
